# Generated by Django 5.1.3 on 2024-11-14 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orca2echo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
