# Generated by Django 5.1.3 on 2024-11-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orca2echo', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField(blank=True, null=True)),
                ('genres', models.CharField(blank=True, max_length=200, null=True)),
                ('cast', models.TextField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=200, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('languages', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
