# Generated by Django 5.1.3 on 2024-11-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orca2echo', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('otp', models.IntegerField(max_length=6, null=True)),
                ('email', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
