# Generated by Django 5.1.3 on 2024-11-14 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orca2echo', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
