# Generated by Django 5.1.3 on 2024-11-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orca2echo', '0006_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.IntegerField(null=True),
        ),
    ]
