# Generated by Django 5.1.3 on 2024-11-14 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orca2echo', '0007_alter_otp_email_alter_otp_id_alter_otp_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
