# Generated by Django 5.1.3 on 2024-11-17 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orca2echo', '0009_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
