# Generated by Django 5.2.16 on 2026-07-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orca2echo', '0010_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
