# Generated by Django 5.2.16 on 2026-07-23 21:00

import uuid
from django.db import migrations, models


def populate_public_ids(apps, schema_editor):
    """Give every existing message its own UUID before the unique constraint.

    A callable default is applied once at the schema level, so adding the field
    unique in a single step would write the same UUID to every row. This fills
    each row individually first; new rows get their default from the model.
    """
    Message = apps.get_model("orca2echo", "Message")
    for message in Message.objects.all().only("id"):
        message.public_id = uuid.uuid4()
        message.save(update_fields=["public_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('orca2echo', '0012_friendship_message_profile_friendrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(populate_public_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='message',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
