"""
Django settings for orca project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv  # type: ignore

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env from project root, regardless of CWD.
#
# override=False is deliberate: a real environment variable must win over the
# .env file. Docker, CI, and systemd all configure the app by exporting
# variables, and the project directory is bind-mounted into the container, so
# override=True would let a developer's local .env silently replace the
# container's MONGO_URL and point the app at the wrong database.
load_dotenv(BASE_DIR / '.env', override=False)

# Quick-start development settings - unsuitable for production
SECRET_KEY = os.environ.get('SECRET_KEY')

DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Comma-separated list of hostnames this app will answer for. Defaults to local
# development only. Never widen this to '*' in a deployment: with DEBUG off,
# Django relies on it to reject forged Host headers.
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')
    if host.strip()
]

_app_url = os.environ.get('APP_URL')
CSRF_TRUSTED_ORIGINS = [_app_url] if _app_url else []

# Dedicated key for profile and conversation tokens. Optional: when unset,
# auth_service.get_fernet() derives a key from SECRET_KEY instead. Setting it
# lets the token key be rotated without invalidating every user session.
FERNET_KEY = os.environ.get('FERNET_KEY')

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',  # Added for WebSocket support
    'orca2echo',  # Ensure this is your app where static files are stored
    'django_user_agents',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise must sit directly below SecurityMiddleware and above
    # everything else, otherwise static files are served through the whole
    # middleware stack (or not served by WhiteNoise at all).
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',  # CSRF middleware included here
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',
]

ROOT_URLCONF = 'orca.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'orca.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

# Static files located in app-specific directories
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'orca2echo', 'static'),  # Updated for app-specific static files
]

# Only needed if you plan to collect static files during deployment
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        # Compresses static files and appends a content hash to each name so
        # they can be cached indefinitely by the browser.
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')

# In settings.py
LOGIN_URL = 'signin'  # Custom login page

# Security headers. Only enforced outside DEBUG so local HTTP development
# still works; without this the session cookie would never be sent over plain
# HTTP on localhost and signin would appear to silently fail.
SECURE_CONTENT_TYPE_NOSNIFF = True
SESSION_COOKIE_HTTPONLY = True
X_FRAME_OPTIONS = 'DENY'

# Django's default report filter masks SECRET_KEY and EMAIL_HOST_PASSWORD but
# not MONGO_URL, which embeds its own username and password. Without this a
# single unhandled exception under DEBUG would print the database credentials
# into the browser.
DEFAULT_EXCEPTION_REPORTER_FILTER = 'orca.reporting.OrcaExceptionReporterFilter'

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True') == 'True'
    # Honour the scheme forwarded by a reverse proxy such as nginx.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # HTTP Strict Transport Security. Off by default on purpose: once a
    # browser has seen this header it refuses plain HTTP for the whole
    # duration, which cannot be undone by changing the server back. Turn it on
    # (31536000 is one year) only once HTTPS is confirmed working on every
    # subdomain you serve.
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0'))
    if SECURE_HSTS_SECONDS:
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True
        SECURE_HSTS_PRELOAD = True

# Media files settings
MEDIA_URL = '/media/'  # URL prefix for serving media files
MEDIA_ROOT = os.path.join(BASE_DIR, 'orca2echo', 'media')  # Path to the media directory

ASGI_APPLICATION = 'orca.asgi.application'

# Redis backs the Channels layer. Configurable so the app works both locally
# and under docker compose, where Redis is a separate service host.
REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379')

# channels_redis parks on BZPOPMIN for brpop_timeout (5) seconds at a time
# while waiting for group messages. redis-py 8.0 started defaulting
# socket_timeout to 5 seconds as well, so the client read deadline and the
# server block time expire together and whichever lands first is a coin flip.
# When the read deadline wins, redis-py raises
# "TimeoutError: Timeout reading from <host>" and the consumer dies mid-chat.
# Giving the socket a longer deadline than the blocking read keeps the timeout
# meaningful for genuinely dead connections without tripping on idle polls.
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [{"address": REDIS_URL, "socket_timeout": 30}],
        },
    },
}

# Used for signin rate limiting. Redis when available so the limit holds across
# worker processes; local memory otherwise, which keeps tests and a bare
# checkout runnable without a Redis server.
if os.environ.get('REDIS_URL'):
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'orca-default-cache',
        }
    }

VAPID_PRIVATE_KEY = os.environ.get('VAPID_PRIVATE_KEY')
VAPID_PUBLIC_KEY = os.environ.get('VAPID_PUBLIC_KEY')

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'django_app.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'orca2echo': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
